# Supply chain defense
minimumReleaseAge: 10080 # packages must be older than 7 days
minimumReleaseAgeStrict: true # always refuse
blockExoticSubdeps: true # blocks git URLs and raw tarballs
trustPolicy: no-downgrade # refuse versions in which the trust-evidence level decreases
trustPolicyIgnoreAfter: 10080 # overrule the rule above after 7 days (should be okay)
allowBuilds:
  "@parcel/watcher": true
  cypress: true
  ffmpeg-static: true
  msw: true
  sharp: true
  unrs-resolver: true
