name: update
run-name: Updating changes on server
concurrency: production
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    environment: production
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PKEY" > ~/.ssh/pk
          chmod 600 ~/.ssh/pk
          cat >>~/.ssh/config <<END
          Host server
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/pk
            StrictHostKeyChecking no
          END
        env:
          SSH_PKEY: ${{ secrets.SSH_PKEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
      - name: Pull Changes
        run: ssh server 'cd heardle && git pull'
      - name: Rebuild
        run: ssh server 'cd heardle && npm i && npm run build && pm2 restart heardle'
